// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorTest.Data.Models
{
    public partial class Grocery
    {
        public Grocery()
        {
            StoreAreaMember = new HashSet<StoreAreaMember>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public double DefaultAmount { get; set; }
        public string DefaultUnit { get; set; }

        public virtual Category Category { get; set; }
        public virtual Need Need { get; set; }
        public virtual ICollection<StoreAreaMember> StoreAreaMember { get; set; }
    }
}