// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorTest.Data.Models
{
    public partial class StoreArea
    {
        public StoreArea()
        {
            StoreAreaMember = new HashSet<StoreAreaMember>();
        }

        public int Id { get; set; }
        public int StoreId { get; set; }
        public string Name { get; set; }

        public virtual Store Store { get; set; }
        public virtual ICollection<StoreAreaMember> StoreAreaMember { get; set; }
    }
}