// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorTest.Data.Models
{
    public partial class Store
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}